# .github/workflows/deploy.yml
name: Deploy Vite app to GitHub Pages

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # or the node version you want

      - name: Install dependencies
        run: |
          cd frontend
          npm install --legacy-peer-deps

      - name: Build the project
        run: |
          cd frontend
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
          # Optional: specify user name/email for commit
          # user_name: github-actions
          # user_email: github-actions@github.com
